---
- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest
    update_cache: yes

- name: Add user to group root
  user:
    name: "{{ user }}"
    groups: root
    state: present