---
- name: Install docker
  ansible.builtin.dnf:
    name: docker
    state: latest
    update_cache: true

- name: Start Docker 
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: docker
    append: true