---
- name: Run github oauth2 proxy container
  community.docker.docker_container:
    name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy
    volumes:
      - ~/auth-emails:/auth-emails:ro
    ports:
      - "127.0.0.1:4180:4180"
    env:
      OAUTH2_PROXY_PROVIDER: "gitlab"
      OAUTH2_PROXY_SCOPE: "openid email"
      OAUTH2_PROXY_OIDC_ISSUER_URL: "https://gitlab.com"
      OAUTH2_PROXY_CLIENT_ID: "{{ CLIENT_ID_GITLAB }}"
      OAUTH2_PROXY_CLIENT_SECRET: "{{ CLIENT_SECRET_GITLAB }}"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_UPSTREAM: "file:///dev/null"
      OAUTH2_PROXY_REDIRECT_URL: "http://98.93.113.163/oauth2/callback"
      OAUTH2_PROXY_COOKIE_SECRET: "{{ COOKIE_SECRET }}"
      OAUTH2_PROXY_COOKIE_SECURE: "false"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
      OAUTH2_PROXY_AUTHENTICATED_EMAILS_FILE: /auth-emails
      OAUTH2_PROXY_WHITELIST_DOMAINS: "98.93.113.163"